// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVX-NvjO2z_VYh51EVbqeP5sAQ3Pebz-I',
    appId: '1:368781005008:web:c38ca9454f60dfdd7f4ed5',
    messagingSenderId: '368781005008',
    projectId: 'argo-parcel-app-backend',
    authDomain: 'argo-parcel-app-backend.firebaseapp.com',
    storageBucket: 'argo-parcel-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUio7R1G2EiKPclVl-8WLEClDEvq4D1YQ',
    appId: '1:368781005008:android:15bd3a175556fb517f4ed5',
    messagingSenderId: '368781005008',
    projectId: 'argo-parcel-app-backend',
    storageBucket: 'argo-parcel-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUBbQKiPAqXt8wSO9TVhax5t3cv7kPOsQ',
    appId: '1:368781005008:ios:0ee6044bd568bc597f4ed5',
    messagingSenderId: '368781005008',
    projectId: 'argo-parcel-app-backend',
    storageBucket: 'argo-parcel-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.parcelApp',
  );
}
